import type { Metadata } from "next";
import { Blinker } from "next/font/google";

const blinker = Blinker({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blinker.className} antialiased`}>{children}</body>
    </html>
  );
}
